### PR TITLE
Rename pom.xml to pog.xml

### PR DESCRIPTION
**Pull request by Dejwut**
### Hello Lucas

I like your project, but you mispel "pok" to "pom",

You're welcom

### CODE REVIEW

**Comment by lhridder** [comment]
This not fuck up my repo yes?

**Comment by Leastrio** [comment]
Yes it will improve speed of repo

**Comment by Dejwut** [comment]
Yes it says no conflicts and will make this repo poggers, now please just click the merge button, thank.

**Review by lhridder — CHANGES_REQUESTED** [review]
pls explain why line 32 different

**Review by Leastrio — APPROVED** [review]
lgtm!

**Pull request merged**
